#!/bin/bash

if [ "$1" == "configure" ]; then
	# Append specific values in PATH
	if [ ! -f /etc/profile.d/01-cluepath.sh ]; then
		echo "PATH=/opt/clue/bin:\$PATH" >/etc/profile.d/01-cluepath.sh
		echo "export PATH" >>/etc/profile.d/01-cluepath.sh
		chmod +x /etc/profile.d/01-cluepath.sh
		. /etc/profile.d/01-cluepath.sh
	fi

	# Append specific values in PYTHONPATH
	if [ ! -f /etc/profile.d/02-cluepypath.sh ]; then
		echo "PYTHONPATH=/opt/clue/lib/python2.7/dist-packages:\$PYTHONPATH" >/etc/profile.d/02-cluepypath.sh
		echo "export PYTHONPATH" >>/etc/profile.d/02-cluepypath.sh
		chmod +x /etc/profile.d/02-cluepypath.sh
		. /etc/profile.d/02-cluepypath.sh
	fi

	# Set script permissions and Register service
	chmod +x /etc/init.d/clue-picam
	chmod +x /opt/clue/bin/picam
	/usr/sbin/update-rc.d clue-picam defaults >/dev/null 2>&1
	/bin/systemctl daemon-reload >/dev/null 2>&1

	# Restart the servicee (if is the case)
	if [ $(ps -ef | grep "picam" | grep -v "grep" | grep -v "apt" | grep -v "dpkg" | wc -l) -ne 0 ]; then
		service clue-picam restart >/dev/null 2>&1
	fi
fi